// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: internal/protocol/cend/protobuf/message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_AUTH          MessageType = 0 // 鉴权
	MessageType_AUTH_ACK      MessageType = 1 // 鉴权响应
	MessageType_HEARTBEAT     MessageType = 2 // 心跳
	MessageType_HEARTBEAT_ACK MessageType = 3 // 心跳响应
	MessageType_MESSAGE       MessageType = 4 // 业务消息
	MessageType_MESSAGE_ACK   MessageType = 5 // 业务消息响应
	MessageType_PUSH          MessageType = 6 // 服务端推送
	MessageType_ERROR         MessageType = 7 // 错误
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "AUTH",
		1: "AUTH_ACK",
		2: "HEARTBEAT",
		3: "HEARTBEAT_ACK",
		4: "MESSAGE",
		5: "MESSAGE_ACK",
		6: "PUSH",
		7: "ERROR",
	}
	MessageType_value = map[string]int32{
		"AUTH":          0,
		"AUTH_ACK":      1,
		"HEARTBEAT":     2,
		"HEARTBEAT_ACK": 3,
		"MESSAGE":       4,
		"MESSAGE_ACK":   5,
		"PUSH":          6,
		"ERROR":         7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_cend_protobuf_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_protocol_cend_protobuf_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{0}
}

// 消息头
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         uint32                 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`                     // 魔数
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                 // 版本
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=cend.MessageType" json:"type,omitempty"` // 消息类型
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`                         // 序列号
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`             // 时间戳
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`   // 链路追踪ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetMagic() uint32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_AUTH
}

func (x *Header) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 鉴权请求
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                             // JWT Token
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备ID
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // App版本
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                   // 操作系统
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`    // 系统版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *AuthRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AuthRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

// 鉴权响应
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                            // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                       // 消息
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`  // 会话ID
	ExpiresAt     uint64                 `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthResponse) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// 心跳
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    uint64                 `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // 客户端时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetClientTime() uint64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// 心跳响应
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    uint64                 `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // 服务端时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatAck) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 业务消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // 请求ID
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                                                                                   // 发送者
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                                                                                       // 接收者
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 内容
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // 确保有 type 字段
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Timestamp     uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 消息响应
type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                           // 状态码
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // 消息
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MessageAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MessageAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 推送消息
type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                                        // 消息ID
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                                                                                   // 来源
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                             // 内容
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{7}
}

func (x *PushMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PushMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PushMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PushMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 错误响应
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cend_protobuf_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protocol_cend_protobuf_message_proto protoreflect.FileDescriptor

const file_internal_protocol_cend_protobuf_message_proto_rawDesc = "" +
	"\n" +
	"-internal/protocol/cend/protobuf/message.proto\x12\x04cend\"\xaa\x01\n" +
	"\x06Header\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\rR\x05magic\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.cend.MessageTypeR\x04type\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"\x90\x01\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\"z\n" +
	"\fAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x04R\texpiresAt\",\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x04R\n" +
	"clientTime\"/\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x04R\n" +
	"serverTime\"\x8e\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x127\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1b.cend.Message.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"\xf2\x01\n" +
	"\vPushMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.cend.PushMessage.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*z\n" +
	"\vMessageType\x12\b\n" +
	"\x04AUTH\x10\x00\x12\f\n" +
	"\bAUTH_ACK\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\x11\n" +
	"\rHEARTBEAT_ACK\x10\x03\x12\v\n" +
	"\aMESSAGE\x10\x04\x12\x0f\n" +
	"\vMESSAGE_ACK\x10\x05\x12\b\n" +
	"\x04PUSH\x10\x06\x12\t\n" +
	"\x05ERROR\x10\aB!Z\x1finternal/protocol/cend/protobufb\x06proto3"

var (
	file_internal_protocol_cend_protobuf_message_proto_rawDescOnce sync.Once
	file_internal_protocol_cend_protobuf_message_proto_rawDescData []byte
)

func file_internal_protocol_cend_protobuf_message_proto_rawDescGZIP() []byte {
	file_internal_protocol_cend_protobuf_message_proto_rawDescOnce.Do(func() {
		file_internal_protocol_cend_protobuf_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_cend_protobuf_message_proto_rawDesc), len(file_internal_protocol_cend_protobuf_message_proto_rawDesc)))
	})
	return file_internal_protocol_cend_protobuf_message_proto_rawDescData
}

var file_internal_protocol_cend_protobuf_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_cend_protobuf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_protocol_cend_protobuf_message_proto_goTypes = []any{
	(MessageType)(0),      // 0: cend.MessageType
	(*Header)(nil),        // 1: cend.Header
	(*AuthRequest)(nil),   // 2: cend.AuthRequest
	(*AuthResponse)(nil),  // 3: cend.AuthResponse
	(*Heartbeat)(nil),     // 4: cend.Heartbeat
	(*HeartbeatAck)(nil),  // 5: cend.HeartbeatAck
	(*Message)(nil),       // 6: cend.Message
	(*MessageAck)(nil),    // 7: cend.MessageAck
	(*PushMessage)(nil),   // 8: cend.PushMessage
	(*ErrorResponse)(nil), // 9: cend.ErrorResponse
	nil,                   // 10: cend.Message.MetadataEntry
	nil,                   // 11: cend.PushMessage.MetadataEntry
}
var file_internal_protocol_cend_protobuf_message_proto_depIdxs = []int32{
	0,  // 0: cend.Header.type:type_name -> cend.MessageType
	10, // 1: cend.Message.metadata:type_name -> cend.Message.MetadataEntry
	11, // 2: cend.PushMessage.metadata:type_name -> cend.PushMessage.MetadataEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protocol_cend_protobuf_message_proto_init() }
func file_internal_protocol_cend_protobuf_message_proto_init() {
	if File_internal_protocol_cend_protobuf_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_cend_protobuf_message_proto_rawDesc), len(file_internal_protocol_cend_protobuf_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_cend_protobuf_message_proto_goTypes,
		DependencyIndexes: file_internal_protocol_cend_protobuf_message_proto_depIdxs,
		EnumInfos:         file_internal_protocol_cend_protobuf_message_proto_enumTypes,
		MessageInfos:      file_internal_protocol_cend_protobuf_message_proto_msgTypes,
	}.Build()
	File_internal_protocol_cend_protobuf_message_proto = out.File
	file_internal_protocol_cend_protobuf_message_proto_goTypes = nil
	file_internal_protocol_cend_protobuf_message_proto_depIdxs = nil
}
